import type { AIProvider } from "../../stores/aiSettingsStore";

export interface AIModelOption {
  id: string;
  label: string;
  free?: boolean;
  group?: string;
}

export const MODELS_BY_PROVIDER: Record<AIProvider, AIModelOption[]> = {
  anthropic: [
    { id: "claude-opus-4-7", label: "Claude Opus 4.7" },
    { id: "claude-sonnet-4-6", label: "Claude Sonnet 4.6" },
    { id: "claude-haiku-4-5-20251001", label: "Claude Haiku 4.5" },
  ],
  openai: [
    { id: "auto", label: "Auto" },
    { id: "gpt-5.5", label: "GPT-5.5" },
    { id: "gpt-5.5-pro", label: "GPT-5.5 Pro" },
    { id: "gpt-5.4", label: "GPT-5.4" },
    { id: "gpt-5.4-mini", label: "GPT-5.4 Mini" },
    { id: "gpt-5.4-nano", label: "GPT-5.4 Nano" },
    { id: "gpt-5.3-codex", label: "GPT-5.3 Codex" },
    { id: "gpt-5.2", label: "GPT-5.2" },
    { id: "gpt-5.2-codex", label: "GPT-5.2 Codex" },
    { id: "gpt-5.1-codex-max", label: "GPT-5.1 Codex Max" },
    { id: "gpt-5.1-codex", label: "GPT-5.1 Codex" },
    { id: "gpt-5.1-codex-mini", label: "GPT-5.1 Codex Mini" },
  ],
  openrouter: [
    { id: "openrouter/free", label: "Auto Free", free: true, group: "Free" },
    { id: "nousresearch/hermes-3-llama-3.1-405b:free", label: "Hermes 3 405B", free: true, group: "Free" },
    { id: "qwen/qwen3-coder:free", label: "Qwen3 Coder 480B", free: true, group: "Free" },
    { id: "openai/gpt-oss-120b:free", label: "GPT-OSS 120B", free: true, group: "Free" },
    { id: "nvidia/nemotron-3-super-120b-a12b:free", label: "Nemotron 3 Super 120B", free: true, group: "Free" },
    { id: "qwen/qwen3-next-80b-a3b-instruct:free", label: "Qwen3 Next 80B", free: true, group: "Free" },
    { id: "meta-llama/llama-3.3-70b-instruct:free", label: "Llama 3.3 70B", free: true, group: "Free" },
    { id: "minimax/minimax-m2.5:free", label: "MiniMax M2.5", free: true, group: "Free" },
    { id: "z-ai/glm-4.5-air:free", label: "GLM 4.5 Air", free: true, group: "Free" },
    { id: "google/gemma-4-31b-it:free", label: "Gemma 4 31B", free: true, group: "More Free" },
    { id: "google/gemma-4-26b-a4b-it:free", label: "Gemma 4 26B", free: true, group: "More Free" },
    { id: "google/gemma-3-27b-it:free", label: "Gemma 3 27B", free: true, group: "More Free" },
    { id: "nvidia/nemotron-3-nano-30b-a3b:free", label: "Nemotron 3 Nano 30B", free: true, group: "More Free" },
    { id: "openai/gpt-oss-20b:free", label: "GPT-OSS 20B", free: true, group: "More Free" },
    { id: "arcee-ai/trinity-large-preview:free", label: "Trinity Large 400B", free: true, group: "More Free" },
    { id: "anthropic/claude-opus-4.6", label: "Claude Opus 4.6", group: "Anthropic" },
    { id: "anthropic/claude-sonnet-4.6", label: "Claude Sonnet 4.6", group: "Anthropic" },
    { id: "anthropic/claude-haiku-4.5", label: "Claude Haiku 4.5", group: "Anthropic" },
    { id: "openai/gpt-5.5", label: "GPT-5.5", group: "OpenAI" },
    { id: "openai/gpt-5.5-pro", label: "GPT-5.5 Pro", group: "OpenAI" },
    { id: "openai/gpt-5.4", label: "GPT-5.4", group: "OpenAI" },
    { id: "openai/gpt-5.2", label: "GPT-5.2", group: "OpenAI" },
    { id: "openai/gpt-5.1", label: "GPT-5.1", group: "OpenAI" },
    { id: "google/gemini-3.1-pro-preview", label: "Gemini 3.1 Pro", group: "Google" },
    { id: "google/gemini-3-pro-preview", label: "Gemini 3 Pro", group: "Google" },
    { id: "google/gemini-3-flash-preview", label: "Gemini 3 Flash", group: "Google" },
    { id: "deepseek/deepseek-v4-pro", label: "DeepSeek V4 Pro", group: "DeepSeek" },
    { id: "deepseek/deepseek-v4-flash", label: "DeepSeek V4 Flash", group: "DeepSeek" },
    { id: "deepseek/deepseek-v3.2", label: "DeepSeek V3.2", group: "DeepSeek" },
    { id: "deepseek/deepseek-v3.2-speciale", label: "DeepSeek V3.2 Speciale", group: "DeepSeek" },
    { id: "deepseek/deepseek-r1", label: "DeepSeek R1", group: "DeepSeek" },
    { id: "x-ai/grok-4.20", label: "Grok 4.20", group: "xAI" },
    { id: "x-ai/grok-4.1-fast", label: "Grok 4.1 Fast", group: "xAI" },
    { id: "z-ai/glm-5.1", label: "GLM 5.1", group: "Zhipu" },
    { id: "z-ai/glm-5", label: "GLM 5", group: "Zhipu" },
    { id: "qwen/qwen3.6-plus", label: "Qwen3.6 Plus", group: "Qwen" },
    { id: "qwen/qwen3-coder-next", label: "Qwen3 Coder Next", group: "Qwen" },
    { id: "meta-llama/llama-4-maverick", label: "Llama 4 Maverick", group: "Meta" },
    { id: "mistralai/mistral-large-2512", label: "Mistral Large 3", group: "Mistral" },
  ],
  dashscope: [
    { id: "qwen3.6-plus", label: "Qwen3.6 Plus" },
    { id: "qwen-plus", label: "Qwen Plus" },
    { id: "qwen-turbo", label: "Qwen Turbo" },
    { id: "qwen-max", label: "Qwen Max" },
    { id: "qwen-long", label: "Qwen Long" },
    { id: "deepseek-v4-flash", label: "DeepSeek V4 Flash（便宜快）" },
    { id: "deepseek-v4-pro", label: "DeepSeek V4 Pro（深度思考）" },
  ],
  google: [
    { id: "auto", label: "Auto" },
    { id: "gemini-3-flash", label: "Gemini 3 Flash" },
    { id: "gemini-3-pro-low", label: "Gemini 3 Pro" },
    { id: "gemini-3-pro-high", label: "Gemini 3 Pro (Deep)" },
    { id: "gemini-3.1-pro-low", label: "Gemini 3.1 Pro" },
    { id: "gemini-3.1-pro-high", label: "Gemini 3.1 Pro (Deep)" },
    { id: "claude-sonnet-4-6", label: "Claude Sonnet 4.6" },
    { id: "claude-opus-4-6-thinking", label: "Claude Opus 4.6" },
  ],
  minimax: [
    { id: "MiniMax-M2.7", label: "MiniMax M2.7" },
    { id: "MiniMax-M2.5", label: "MiniMax M2.5" },
    { id: "MiniMax-M2.1", label: "MiniMax M2.1" },
  ],
  deepseek: [
    { id: "deepseek-v4-flash", label: "DeepSeek V4 Flash（便宜快）" },
    { id: "deepseek-v4-pro", label: "DeepSeek V4 Pro（旗舰）" },
  ],
  ollama: [
    { id: "llama3.1", label: "Llama 3.1" },
    { id: "qwen2.5", label: "Qwen 2.5" },
    { id: "gemma2", label: "Gemma 2" },
    { id: "mistral", label: "Mistral" },
  ],
  lmstudio: [],
  custom: [],
};

export const PROVIDER_LABELS: Record<AIProvider, string> = {
  anthropic: "Anthropic",
  openai: "OpenAI",
  openrouter: "OpenRouter",
  dashscope: "Qwen",
  google: "Google",
  minimax: "MiniMax",
  deepseek: "DeepSeek",
  ollama: "Ollama（本地）",
  lmstudio: "LM Studio（本地）",
  custom: "自定义",
};
